### PR TITLE
Remove flag `--home` in CLI command `vatz init`

### LINKED ISSUE #444: Get rid of homepath flag `--home` In CLI  `./vatz init`
### Checklist
- [x] Bug from Service (Vatz)
- [ ] Bug from Plugin (Vatz) 
- [ ] Malfunction on CI/CD 
- [ ] etc(e.g, Hardware version doesn't match, )

---

since we moved home_path setting into default.yaml (config file) 
we do not need flag `--home` in CLI command ./vatz init. 
and it doesn't work anymore.  

```
 ./vatz init --all                         
Error: flag needs an argument: --all
Usage:
   init [flags]

Flags:
  -a, --all string      Set default config.yaml include default vatz-plugin-sysutil
  -h, --help            help for init
  -p, --home string     Home directory of VATZ (default "~/.vatz")
  -o, --output string   New config file to create (default "default.yaml")
```

Get rid of flag `--home`

### PR DESCRIPTION
**Pull request by xellos00**
### 1. Type of change

Please delete options that are not relevant.

- [ ] New feature
- [ ] Enhancement
- [x] Bug/fix (non-breaking change which fixes an issue)
- [ ] others (anything other than above)

---

close #444 

**Summary**

We do not use --home flag in CLI `vatz init` anymore since homepath is set up in config yaml file. 
- Extended default reminder schedule interval from 15 to 30
- Removed --home setting from command `vatz init`

---
```
 ✘ dongyookang DK 💡   ~/ffplay/GolandProjects/xellos/vatz   ISSUE-444
 make coverage
fatal: No names found, cannot describe anything.
?       github.com/dsrvlabs/vatz        [no test files]
?       github.com/dsrvlabs/vatz/manager/types  [no test files]
?       github.com/dsrvlabs/vatz/mocks  [no test files]
ok      github.com/dsrvlabs/vatz/cmd    1.092s  coverage: 18.3% of statements
ok      github.com/dsrvlabs/vatz/manager/api    0.363s  coverage: 0.0% of statements [no tests to run]
ok      github.com/dsrvlabs/vatz/manager/config 0.500s  coverage: 79.4% of statements
ok      github.com/dsrvlabs/vatz/manager/dispatcher     0.636s  coverage: 7.8% of statements
ok      github.com/dsrvlabs/vatz/manager/executor       1.067s  coverage: 68.9% of statements
ok      github.com/dsrvlabs/vatz/manager/healthcheck    0.770s  coverage: 46.5% of statements
ok      github.com/dsrvlabs/vatz/manager/plugin 5.405s  coverage: 50.6% of statements
ok      github.com/dsrvlabs/vatz/monitoring/prometheus  1.214s  coverage: 0.0% of statements
ok      github.com/dsrvlabs/vatz/rpc    2.496s  coverage: 67.2% of statements
ok      github.com/dsrvlabs/vatz/utils  1.342s  coverage: 7.1% of statements
 dongyookang DK 💡   ~/ffplay/GolandProjects/xellos/vatz   ISSUE-444 ±
 
```

### CODE REVIEW

File: cmd/init.go [hunk 1]
```diff
@@ -28,7 +27,7 @@ func createInitCommand(initializer tp.Initializer) *cobra.Command {
   notification_info:
     host_name: "Put your machine's host name"
     default_reminder_schedule:
-      - "*/15 * * * *"
+      - "*/30 * * * *"
```
Comment (meetrick) [inline cmd/init.go:30]: Why did the reminder schedule change?
It looks like a different fix than what this PR is for!

**Review by meetrick — COMMENTED** [review]
Please check my comment

File: cmd/init.go (hunk 1 above)
Comment (xellos00) [reply cmd/init.go:30]: because current reminder sending notification way too often and so I think it is good to fix that too as well. it's merely reminder schedule and I mentioned it on the PR SUMMARY.

Comment (rootwarp) [reply cmd/init.go:30]: @meetrick agree.

File: cmd/init.go [hunk 2]
```diff
@@ -15,7 +14,7 @@ import (
 func createInitCommand(initializer tp.Initializer) *cobra.Command {
 	cmd := &cobra.Command{
 		Use:   "init",
-		Short: "Init",
+		Short: "init",
```
Comment (rootwarp) [inline cmd/init.go:17]: God. you have eagle eyes. 👀

**Comment by xellos00** [comment]
@meetrick 
@rootwarp 

I revert back reminder interval and will handle this change in another issue.
Can you guys approve this PR?

```
 dongyookang DK ⚡️   ~/ffplay/GolandProjects/xellos/vatz   ISSUE-444
 make build        
fatal: No names found, cannot describe anything.
go build -ldflags="-X 'github.com/dsrvlabs/vatz/utils.Version=ISSUE-444' -X 'github.com/dsrvlabs/vatz/utils.Commit=e3a40ba'" -v
github.com/dsrvlabs/vatz/cmd
github.com/dsrvlabs/vatz
 dongyookang DK ⚡️   ~/ffplay/GolandProjects/xellos/vatz   ISSUE-444
 make coverage
fatal: No names found, cannot describe anything.
?       github.com/dsrvlabs/vatz        [no test files]
?       github.com/dsrvlabs/vatz/manager/types  [no test files]
?       github.com/dsrvlabs/vatz/mocks  [no test files]
ok      github.com/dsrvlabs/vatz/cmd    1.267s  coverage: 18.3% of statements
ok      github.com/dsrvlabs/vatz/manager/api    0.347s  coverage: 0.0% of statements [no tests to run]
ok      github.com/dsrvlabs/vatz/manager/config 0.475s  coverage: 79.4% of statements
ok      github.com/dsrvlabs/vatz/manager/dispatcher     0.613s  coverage: 7.8% of statements
ok      github.com/dsrvlabs/vatz/manager/executor       0.755s  coverage: 68.9% of statements
ok      github.com/dsrvlabs/vatz/manager/healthcheck    0.896s  coverage: 46.5% of statements
ok      github.com/dsrvlabs/vatz/manager/plugin 6.180s  coverage: 50.6% of statements
ok      github.com/dsrvlabs/vatz/monitoring/prometheus  1.198s  coverage: 0.0% of statements
ok      github.com/dsrvlabs/vatz/rpc    2.358s  coverage: 67.2% of statements
ok      github.com/dsrvlabs/vatz/utils  1.487s  coverage: 7.1% of statements
 dongyookang DK ⚡️   ~/ffplay/GolandProjects/xellos/vatz   ISSUE-444

```

**Review by heejin-github — APPROVED** [review]
LGTM

File: cmd/init.go (hunk 1 above)
Comment (xellos00) [reply cmd/init.go]: It's removed from this PR.

**Review by rootwarp — APPROVED** [review]
LGTM

**Review by meetrick — APPROVED** [review]
LGTM
